### ISSUE TITLE
Préparation du back

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#101]
- [x] ajouter un attribut `regular` sur le model `Mission` permettant de différencier le type de mission (régulière ou ponctuelle)
- [x] adapter le `#new` (dropdown)
- [x] adapter le controller `mission`
- [x] update seed: créer des missions ponctuelles, et des missions régulières
- [x] retirer les appels à l'API GoogleMap (sera utlisé dans la partie `Producteurs` à la place

**Comment by CitizenYY** [comment]
oki vu merci chief, j'arrivais pas à démarrer car je me perdais dans les profondeurs de l'historique des commits ;)

**Comment by Mate2xo** [comment]
ça roule :) Je vais essayer de développer les issues au fur et à mesure. On a déjà de quoi bosser là
