### ISSUE TITLE
Tests de controller

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#116]
Commences par tester l'accès aux 2 pages publiques du site (GET) pour t'échauffer (`static_pages_controller`).
Ensuite dans `productors_controller`, vérifie que les pages du site interne sont bien accéssibles pour les `member` : pour ça tu devras utiliser un helper Devise pour te logger, et utliser FactoryBot pour créer des fake member.
Ensuite vérifie que l'édition/creation des producteurs est bien réservée aux admins.

Tu peux essayer d'utiliser le générateur Rails pour créer les fichiers `spec` (test) qui n'existent pas.

Le controller est un peu sale, et les authorizations sont gérées par la gem Pundit (fichiers `..._policy`), donc tu n'auras pas de config à faire en théorie, simplement de la vérif. Si tu trouve un edge case d'authorisation qui doit être modifié, ce sera l'occasion de toucher à Pundit.

Récap : 
- [x] vérifier que les pages publiques sont accessible dans le `static_pages_controller`
- [ ] `index`, `show` doivent être visibles par les `member`
- [ ] `new`, `create`, `edit`, `update`, `destroy` ne doivent être accessibles que par les `super_admin`
- [ ] nettoyer le controller là où c'est necessaire
- [ ] modifier les policy de Pundit là où c'est necessaire

**Comment by CitizenYY** [comment]
Yo, petite question : quand tu dis _Ensuite dans productors_controller, vérifie que les pages du site interne sont bien accéssibles pour les member_ => vérifier en écrivant les Tests d'intégration et non à la mano en local je suppose ? ;)

Par contre c'est chiant que le CI ne puisse se lancer à chaque fois que je finis une sous-tâche - [ ] , je ne sais pas s'il y a moyen..

**Comment by Mate2xo** [comment]
le CI ne se lance que quand tu pousses ta branche. Si tu veux des retours de test en developpement, utilise `bundle exec guard` dans le répertoire de l'app.
Pas besoin d'un test d'integration, tu peux juste vérifier la réponse à une requête :
- utilisateur lambda -> redirection
- member loggé -> success

**Comment by Mate2xo** [comment]
Fermeture car travail effectué dans le cadre du refactor des controller
