### ISSUE TITLE
Catégorisation des producteurs

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#128]
Les producteurs doivent être retrouvables par catégorie (Local, Fournisseur)

## To Do

- [x] mettre un attribut `local` booleen sur Productor (`default: false`)
- [x] vérifier la compatibilité avec les anciennes entrées dans la DB

## Must Have

- [x] front : navigation à travers les 2 catégories via des onglets (`Locaux`, `Fournisseurs`)

```gherkin
Scenario: looking for a local productor
  Given I am a logged member
  When I go to the productors index page
  Then I should see a list of local productors

Scenario: looking for a non-local productor
  Given I am a logged member
  When I go to the productors index page
  And click on the `Fournisseurs` tab
  Then I shoud see a list of non-local productors
```

**Comment by Mate2xo** [comment]
OK

**Comment by ghost** [comment]
Du nouveau Tim concernant le design du site ? Je pense attaquer ça dans pas lgt !

Envoyé de mon iPhone

Le 25 juil. 2019 à 11:58, Tim <notifications@github.com<mailto:notifications@github.com>> a écrit :


OK

**Comment by Mate2xo** [comment]
Non pas de news pour l'instant. On va mettre le site en "version beta" cette aprèm en faisant venir des membres pour utiliser le site et avoir des retours.
On se prend un verre pour discuter des retours?
