### ISSUE TITLE
(8)Plannings fixes - du point de vue d'un membre

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#225]
Tout le monde aura un planning fixe d'office pour les permanences.

## 2 types de personnes : fixe ou volant

* les volants travaillent généralement 1h30
* le groupe adhérent aura la main sur la détermination de ce type

## 4 types : semaine A, B, C, D

* Les personnes fixes, choisissent leur type de semaine, le jour et le créneau la première fois. Ensuite le choix est vérouillé. Il faudra alors voir un admin ou un groupe qui a la responsabilité de cette feature
* Les personnes volantes s'inscrivent comme elles veulent

## En tant que

Membre à planning fixe qui n'a pas encore choisi sa semaine de planning (ex: semaine 'A')

### Quand 

je choisi un créneau sur le planning

### Comportement souhaité

* je me retrouve inscrit dans ce créneau pour toute les occurences futures de la semaine choisie (mais pas aux occurences passées)
* ce créneau est ensuite non modifiable, sauf par un admin

## Informations supplémentaires

- Mettre un attribut déterminant si le membre est 'volant' ou 'fixe'
- Mettre un attribut déterminant si le membre a chosi son type de semaine ou pas

**Comment by Floury-Fabio** [comment]
The related pr is merged
