### ISSUE TITLE
(13)Récurrence des créneaux

### ISSUE THREAD

**Issue by Mate2xo** [Mate2xo/THP-Creeons_la_coop#227]
## En tant que

Admin ou gestionnaire de créneau
 
## Quand 

je modifie un créneau

## Comportement actuel

Les autres récurrences de ce créneaux ne sont pas modifées

## Comportement souhaité

je veux avoir la possibilité de pouvoir répercuter les modifications sur les autre récurrences de ce créneau

**Comment by Floury-Fabio** [comment]
This issue is solved by https://github.com/Mate2xo/Creeons_la_coop/pull/268
